name : new workflow

on: 
  push:
    branches: 
       - master
  schedule:
      - cron: '* 0 0 * *'

jobs:
  runs on: ubuntu latest
  steps: 
    - name: checkout
      uses: actions/@checkout@v3

    - name: node.js
      uses: actions/setup-node@v3


    - name: Install dependancies
      uses: npm Install

    - name: run test
      uses: npm test