name : new workflow

on: 
  push:
    branches: 
       - master
  schedule:
      - cron: '0 1 1 1 1'

jobs:
 build1:
  runs-on: ubuntu latest
  steps: 
    - name: checkout
      uses: actions/checkout@v3

    - name: node.js
      uses: actions/setup-node@v3


    - name: Install dependancies
      run: npm install

    - name: run test
      run: npm test